version: '3'
services:
  webserver:
    build:
      context: ./build/webserver
    container_name: webserver
    restart: always
    volumes:
      - ./src:/var/www/html
    ports:
      - '8080:80'
    links:
      - mariadb
  mariadb:
    build: ./build/mariadb
    volumes:
      - /var/lib/mysql
    expose:
      - '3306'
    environment:
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASS}'
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASS}'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    ports:
      - '8888:80'
    volumes:
      - /sessions
volumes:
  src:

