ALTER TABLE `questions` ADD `date_created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `title`;
ALTER TABLE `users` ADD UNIQUE (id);
ALTER TABLE `users` ADD UNIQUE (email);
ALTER TABLE `user_roles` CHANGE `role_id` `role_id` INT(10) UNSIGNED NULL DEFAULT '0';
ALTER TABLE `user_roles` CHANGE `user_id` `user_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT;
